heading:
  name: "John Doe" # mandatory

subheading:
  - type: links
    content:
      - name: "https://www.johndoeportfolio.com"
        highlight: true
        show_below: false
      - name: "johndoe@email.com"
        highlight: false
        show_below: true
  - type: socials
    content:
      - type: orcid_id
        url: "0000-0000-0000-0000"
        show_below: false
      - type: linkedin
        url: "https://linkedin.com/in/johndoe"
        show_below: false

sections:
  - type: education
    content:
      - university: "Fictional University"
        location: "Imaginaria, Wonderland"
        dates: "September 2021 - June 2024"
        degree: "Bachelor of Science in *Computer Science*"
        honors: "**Magna Cum Laude**"
        thesis_title: "An Exploration of ['Quantum Computing'](https://en.wikipedia.org/wiki/Quantum_computing) in Virtual Environments"
        supervisor: "Dr. Alice Wonder"
      - university: "Imaginary Institute of Technology"
        location: "Nowhere City, Utopia"
        dates: "August 2018 - May 2021"
        degree: "Associate Degree in Artificial Intelligence"
        supervisor: "Dr. Bob Builder"

  - type: experience
    content:
      - name: "Professional Experience"
        entity:
          - organization: "Tech Innovations Inc."
            dates: "July 2024 - Present"
            position: "Software Engineer"
            responsibilities:
              - "Developed and maintained cloud-based solutions for various enterprise clients."
              - "Led a team of developers in designing scalable software architectures."
              - "Improved system performance by 30\\% through code optimization and database restructuring."
          - organization: "NextGen Robotics"
            dates: "June 2022 - June 2024"
            position: "Robotics Engineer"
            responsibilities:
              - "Designed and implemented autonomous navigation systems for industrial robots."
              - "Collaborated with cross-functional teams to integrate machine learning models into robotic platforms."

      - name: "Teaching and Volunteering"
        entity:
          - organization: "Virtual Coding Academy"
            dates: "January 2020 - December 2021"
            position: "Instructor"
            supervisor: "Dr. Eve Code"
            department: "Department of Computer Science"
            location: "Imaginaria, Wonderland"
            responsibilities:
              - "Taught introductory and advanced courses in Python programming."
              - "Mentored students on their final projects and provided guidance on coding best practices."
          - organization: "Tech Youth Initiative"
            dates: "July 2019 - June 2020"
            position: "Volunteer Coordinator"
            location: "Nowhere City, Utopia"
            responsibilities:
              - "Organized coding boot camps and hackathons for underprivileged youth."
              - "Managed a team of volunteers and ensured smooth operation of all events."

  - type: bullets
    title: "Honors and Awards"
    description: ""
    content:
      - item: "Dean's List (2023, 2022)"
      - item: "Best Paper Award at Tech Innovations Conference (2023)"
      - item: "Outstanding Graduate Award, Fictional University (2024)"

  - type: newpage

  - type: experience
    content:
      - name: "Certifications"
        entity:
          - organization: "Certified Kubernetes Administrator"
            dates: "Graduated December 2023"
            position: "Cloud Native Computing Foundation"
          - organization: "AWS Certified Solutions Architect"
            dates: "Graduated March 2022"
            position: "Amazon Web Services"

  - type: skills
    content:
      - name: "Spoken Languages"
        data: "English (Fluent), Spanish (Intermediate)"
      - name: "Programming Languages"
        data: "Python, Java, C++, SQL, JavaScript"
      - name: "Tools and Technologies"
        data: "AWS, Docker, Kubernetes, TensorFlow, Git, Jenkins, Linux, Jira"

  - type: bullets
    title: "Professional Activities"
    description: "Served/ing as a reviewer for"
    content:
      - item: "Journals"
        subitems:
          - "Journal of Artificial Intelligence Research (JAIR)"
          - "Journal of Machine Learning Research (JMLR)"
      - item: "Conferences"
        subitems:
          - "IEEE Conference on Computer Vision and Pattern Recognition (CVPR)"
          - "International Conference on Learning Representations (ICLR)"

  - type: talks
    title: "Invited Talks/Workshops"
    content:
      - name: "'AI in Everyday Life', Invited talk, Tech Conference 2023, Imaginaria."
        month: "Nov."
        year: "2023"
      - name: "'Cloud Computing for Beginners', Workshop, FutureTech Expo 2022, Nowhere City."
        month: "Oct."
        year: "2022"
      - name: "'Robotics in Modern Industry', Guest lecture, Imaginary Institute of Technology."
        month: "May"
        year: "2021"
        year: "2024"
      - name: "'Building Scalable Systems with Docker and Kubernetes', Workshop, DevOps World 2023, Tech City."
        month: "Aug."
        year: "2023"
      - name: "'Ethics in AI', Panel discussion, Ethics in Technology Conference 2022, Metropolis."
        month: "Sep."
        year: "2022"

  - type: publications
    title: "Publications"
    bibfile: publications.bib
